data_cfg:
  dataset_name: CCPG
  # dataset_root: /data/CCPG/Released/CCPG-end2end-pkl/
  dataset_root: /lab/yusq_lab/dataset/gait/ccpg/CCPG-end2end-pkl
  dataset_partition: ./datasets/CCPG/CCPG.json
  num_workers: 1
  data_in_use: [True,False,False,False]
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CCPG

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 6000
  save_name: GaitBase_TCLBase_nolinear_sgd
  eval_func: evaluate_CCPG
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: Baseline_TCL
  pretrain_weights_path: pretrained_weights/CCPG/Gaitbase/gaitbase_ccpg.pt
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 100
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16
  cluster_cfg:
    in_channels: 512
    num_parts: 16
    num_clusters: 8
    # hidden_dim: 128
    similarity: euclidean

optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

# optimizer_cfg:
#   lr: 0.1
#   momentum: 0.9
#   solver: SGD
#   weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 5000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 2000
  save_name: GaitBase_TCLBase_nolinear_sgd
  sync_BN: true
  total_iter: 6000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 16 #                 batch_size[1] indicates Samples sequqnce for each Identity
    type: TripletSampler
    collatefn_type: CollateFnTCL
    frames_num_ordered: 100
    frames_num_random: 30
    frames_ordered_skip: 0
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64